### ISSUE TITLE
checksum in the GET /dataobject and GET /databundle endpoints

### ISSUE THREAD

**Issue by ekeilty17** [ga4gh/data-object-service-schemas#112]
In the GET /dataobject and GET /databundle endpoints checksum is a required field. Is the intended use of this parameter to filter dataobjects and databundles by their checksum values? If not then what is the intended use?

**Comment by david4096** [comment]
This is not well specified and should be downgraded to optional. 

The aspiration is to provide reliable checksums over data object checksums. So for example, to verify a bundle one first downloads each data object. Then, by concatenating the checksums, it is possible to verify the contents of the data bundle.

Until this is fully specified and tested, it would probably make sense to remove.
