### ISSUE TITLE
Schema validation warnings

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-object-service-schemas#125]
Schema validates even though there are warnings. I can see them here http://editor.swagger.io/
Maybe the validation test can be tweaked with some `strict=True` option or similar?

**Comment by david4096** [comment]
We used a conversion from another IDL (protobuf) to swagger and it introduced some opinionated mistakes when parsing the comments, like putting the description in improper places.

We should probably close this by deleting those descriptions and providing the necessary documentation at the right level of the hierarchy.
