### ISSUE TITLE
Use `master` as opposed to `develop`

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#14]
Anyone care to offer an opinion here? Using `master` as the main development branch is perhaps more idiomatic.

**Comment by philloooo** [comment]
if you use gitflow then `develop` as the default branch makes sense. Personally I don't like gitflow though :D  we use a branching model similar to what's descrived [here](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow)

**Comment by david4096** [comment]
Since we've updated master against the latest develop we can delete `develop` now.
