### ISSUE TITLE
ID parameter specified three times in PUT /dataobjects/{data_object_id}

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-object-service-schemas#154]
Once in the path, once in `body['data_object_id']`, and once in `body['data_object_id']['id']`.

**Comment by natanlao** [comment]
> But I think that it at least needs to be documented and suggest a default behavior.

Definitely agree - I only point it out since UpdateDataObject on DataBiosphere/dos-azul-lambda doesn't even check for `body.data_object_id`. I think clarification as to how implementations should handle this case would be valuable

**Comment by david4096** [comment]
https://github.com/ga4gh/data-object-service-schemas/blob/master/openapi/data_object_service.swagger.yaml#L912 remove this redundant data_bundle_id and the data_object_id in the UpdateDataObjectRequest.

Also document the workflow of changing an identifier and the reasoning behind having a different ID in the path and request body.
