### ISSUE TITLE
Include swagger-ui, swagger-editor

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#26]
We can host our own static site to go with schemas that visualizes the repositories. This will make it easier to review changes. @briandoconnor

**Comment by psafont** [comment]
Using github pages (ga4gh.github.io) would be a good place to start, a custom hostname could be used later on.

**Comment by denis-yuen** [comment]
We could also use something inside ga4gh.cloud since we own that. 
Like 
dos.ga4gh.cloud
tes.ga4gh.cloud
etc.

**Comment by david4096** [comment]
@briandoconnor Will you add a `gh-pages` branch so I can issue a PR against it?

This is the output on my personal repo:
 https://david4096.github.io/data-object-schemas/

**Comment by david4096** [comment]
This is now available, but being pushed manually:

https://ga4gh.github.io/data-object-schemas/

**Comment by david4096** [comment]
New URL https://ga4gh.github.io/data-object-service-schemas/

Need to add gh-pages push in the .travis.yml.

https://docs.travis-ci.com/user/deployment/pages/
