### ISSUE TITLE
Error handling response types

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/data-object-service-schemas#36]
Servers return 404 on no find. Should we add  response types for 404, 500 ?

**Comment by david4096** [comment]
The protobuf doesn't include error messages and supporting this in a grpc and HTTP1.1 style will be a challenge. To properly cover all error cases we will probably have to act directly on the swagger.

**Comment by buchanae** [comment]
what useful information would an additional error message type be adding to a given http status code? They have precise definitions already: 404 not found, 500 server error, etc.

For example, the PR here: https://github.com/ohsu-comp-bio/dos_connect/pull/18/files
Is just rewording the information specified here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

Except that it's not covering all the bases because it's missing every other status code.

**Comment by denis-yuen** [comment]
https://swagger.io/docs/specification/describing-responses/ touches on this
```
Note that an API specification does not necessarily need to cover all possible HTTP response codes, since they may not be known in advance. However, it is expected to cover successful responses and any known errors. By “known errors” we mean, for example, a 404 Not Found response for an operation that returns a resource by ID, or a 400 Bad Request response in case of invalid operation parameters.
```

In other words, its kind of nice to indicate which error codes are most likely to be returned and thus should be handled as a first priority. 
i.e. 
```
"/ga4gh/dos/v1/databundles": {
       "post": {
       "post": {
         "summary": "Create a new Data Bundle",
         "summary": "Create a new Data Bundle",
         "x-swagger-router-controller": "ga4gh.dos.server",
         "x-swagger-router-controller": "ga4gh.dos.server",
         "operationId": "CreateDataBundle",
         "operationId": "CreateDataBundle",
         "responses": {
         "responses": {
           "200": {
           "200": {
             "description": "",
             "description": "",
             "schema": {
             "schema": {
               "$ref": "#/definitions/ga4ghCreateDataBundleResponse"
               "$ref": "#/definitions/ga4ghCreateDataBundleResponse"
             }
             }
          },
          "401": {
            "description": "Authorization information is missing or invalid."
          },
          "404": {
            "description": "Not found."
          },
          "500": {
            "description": "Unexpected error."
           }
           }
         },
         }
```
means that a client should be prepared to handle 200, 401, 404, and 500 at a minimum. (And conversely, that it probably won't have to consider the 422, 423, 424 webDAV responses as a random example).

**Comment by bwalsh** [comment]
Thanks everyone.  Good discussion.

The  OpenAPI spec [version 3](https://swagger.io/docs/specification/describing-responses/) supports '4XX' style range definitions.  Unfortunately the [version 2](https://swagger.io/docs/specification/2-0/describing-responses/)  spec requires itemizing status codes individually.

The immediate need for documenting the response codes is that without a definition, the bravado client decorates the exception with a 'misconfigured' message.

```
E           HTTPNotFound: 404 NOT FOUND: Response specification matching http status_code 404 not found for operation Operation(GetDataBundle). Either add a response specification for the status_code or use a `default` response.
```
