### ISSUE TITLE
Bravado dependency problems

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#38]
When installing from pypi the bravado fork to support protobuf conversion may not be installed properly. As a workaround:

```
pip install ga4gh-dos-schemas -I --process-dependency-links
```

To close this issue, remove the bravado fork dependency and make alterations at a higher level, or switch to OpenAPI, which avoids the int64 conversion.

**Comment by bwalsh** [comment]
Is it possible to use OpenAPI (Ver 3) ?

**Comment by david4096** [comment]
Bravado relies on OpenAPI v2, so we'll stick with that for now and offer the OpenAPI v3 as experimental.

**Comment by david4096** [comment]
#40 will close this with proper use of SwaggerFormat
