### ISSUE TITLE
Sphinx docs

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#45]
- [ ] Create sphinx documentation from the current markdown documentation. 
- [ ] Add travis read the docs upload script

**Comment by sid10on10** [comment]
I am currently working on it. I have prepared the basic sphinx docs including all markdown files from the project and it's available in my forked copy.

**Comment by sid10on10** [comment]
auto generated conf.py did not pass the flake 8 tests.

**Comment by david4096** [comment]
https://github.com/ga4gh/data-object-service-schemas/pull/60
