### ISSUE TITLE
Sphinx readthedocs

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#56]
Add readthedocs page following #53

**Comment by sid10on10** [comment]
The following error got caught while adding it readthedocs.Webhook activation failed. Make sure you have permissions to set it.

**Comment by david4096** [comment]
Thanks I added a link to rtd, unfortunately I'm gonna have to leave this open since I can't set the web hooks on this repo, its currently pointed at my personal fork

https://data-object-service.readthedocs.io/en/latest/

**Comment by david4096** [comment]
Just set up the webhook (thanks @rishidev!)

We'll close this when someone can confirm a change to the docs is automatically reflected in RTD. (link the successful webhook started build).

**Comment by natanlao** [comment]
Building successfully https://readthedocs.org/projects/data-object-service/builds/7408807/
