### ISSUE TITLE
Improve Open API 3, SmartAPI automation

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#68]
The swagger (OpenAPI 2) description is still the canonical source of schemas. To close this, improve the automation to generate the Open API 3 and SmartAPI definitions by adding scripts that call the required modules to generate output.

Remove the build outputs from the source tree and describe the creation of the OAI3 and SmartAPI descriptions as part of the release and development process.

**Comment by david4096** [comment]
For now, just make sure this section is maintained.

```
servers:
  - url: https://{host}:{port}/{basePath}
    description: The production API server
    variables:
      host:
        default: dos.example.org
        description: The host the service is serving from.
      port:
        enum:
          - '443'
        default: '443'
      basePath:
        # The default base includes a version in the path.
        default: ga4gh/dos/v1
info:
  title: Data Object Service
  version: 0.2.0
  x-implementationLanguage: en
termsOfService: https://www.ga4gh.org/policies/termsandconditions.html
```

**Comment by natanlao** [comment]
It looks like the .smartapi and .openapi files are essentially the same with the exception of the block above - it seems like automating the generation of the .smartapi file by concatenating that block and the .openapi file would be straightforward. (Or by using some kind of templating package like Jinja2 but that seems a little heavy-handed.)

**Comment by cricketsloan** [comment]
➤ Lighthouse Point commented:

[~achave11]   Review
