### ISSUE TITLE
Swagger UI points at inactive service

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#90]
The current github landing pages does not point at a standing service, so "Try It Out!" in the swagger-ui will fail. To close this, point to an active resolver so the github pages swagger UI presents a useful DOS.

**Comment by natanlao** [comment]
#95 disables the "try it out" feature until a resolver is added.

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

I think we can point to dos-azul-lambda to close this:

[https://dos.commons.ucsc-cgp.org](https://dos.commons.ucsc-cgp.org)

**Comment by natanlao** [comment]
I think that would be a good idea once we have full feature parity in dos-azul-lambda
